name: Pre-Merge Code Check

on:
  pull_request:
    branches:
      - main 

jobs:
  # Job for the backend (server)
  server-job:
    runs-on: ubuntu-latest
    container: 
      image: node:20

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install server dependencies
        run: npm ci
        working-directory: ./server 

      - name: Run server tests
        run: npm test
        working-directory: ./server

  # Job for the frontend (client)
  client-job:
    runs-on: ubuntu-latest
    container: 
      image: node:20 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install client dependencies
        run: npm ci
        working-directory: ./client

      - name: Run client tests
        run: npm test
        working-directory: ./client

# Deploy backend (server)
  deploy:
    name: Deploy
    needs: [server-job]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}